
# Add some color for black background

export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# Git branch in prompt.

parse_git_branch() {

    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'

}

export PS1="\u@\h \[\033[32m\] \$(pwd) \[\033[33m\]\$(parse_git_branch)\[\033[00m\]"

# We should start typing on the next line

PS1="$PS1\n\$ "